# Site settings
title: KG7AXD - Portland Oregon USA
email: jason@kg7axd.com
description: > # this means to ignore newlines until "baseurl:"
  Web hole  for amateur radio operator KG7AXD, based in Portland Oregon USA. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kg7axd.com" # the base hostname & protocol for your site
twitter_username: KG7AXD
# github_username:  dropkick

# Build settings

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
include:      [".htaccess"]
exclude:      ["config.codekit"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: pygments
excerpt_separator: "\n\n"

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null
